---
# Fill in vars.yml before running

# Post-provisioning localhost
- name: "SSH key Local provision"
  hosts: localhost
  vars_files:
    - vars/vars.yml
  tasks:
  - name: Install SSH private Key to localhost
    include: tasks/ssh_key_local.yml

# Post-provisioning VM
- name: "Provision Enviorment"
  hosts: all
  become: true
  vars_files:
    - vars/vars.yml
  tasks:

  - name: Collect Server IP
    debug:
      msg: "{{ ansible_ssh_host }}"

  - name: Install Required Packages
    include: tasks/packages.yml

  - name: Install Docker from official signed repo
    include: tasks/docker.yml
    
# Provision Docker Containers om server1

- name: "Provision Enviorment"
  hosts: server1
  become: true
  vars_files:
    - vars/vars.yml
  tasks:

  - name: Collect Server IP
    debug:
      msg: "{{ ansible_ssh_host }}"

  - name: Install Containers
    when: deploy_containers == true
    include: tasks/containers_1.yml

# Provision Docker Containers on server2

- name: "Provision Enviorment"
  hosts: server2
  become: true
  vars_files:
    - vars/vars.yml
  tasks:

  - name: Collect Server IP
    debug:
      msg: "{{ ansible_ssh_host }}"

  - name: Install Containers
    when: deploy_containers == true
    include: tasks/containers_2.yml

# Lock Down SSH and reboot
  # !! preferablly this is the last task, after this task SSH ports will change to 2002 and key auth forced
- name: "Lock Down SSH"
  hosts: all
  become: true
  vars_files:
    - vars/vars.yml
  tasks:
  - name: Setup SSH security
    include: tasks/ssh_security.yml
