#  localhost play
- name: Creates .ssh hidden folder in root dir
  file:
      path: "/root/.ssh"
      state: directory

- name: remove known hosts defaults
  file:
      path: "root/.ssh/known_hosts"
      state: absent

# IF ssh key is present it will use that one

- name: Check if Keys are already present
  stat:
    path: /workspaces/{{repo_name}}/defaults/.generated_keys/id_rsa
  register: ssh_keys_exist

- name: Change file ownership
  when: ssh_keys_exist.stat.exists
  ansible.builtin.file:
    path: /workspaces/{{repo_name}}/defaults/.generated_keys/id_rsa.pub
    mode: '400'

- name: Copy a existing "id_rsa.pub' file from dev container to the .ssh folder on container
  when: ssh_keys_exist.stat.exists
  copy:
    src: "/workspaces/{{repo_name}}/defaults/.generated_keys/id_rsa.pub"
    dest: "/root/.ssh/id_rsa.pub"

- name: Copy a existing "id_rsa'file from dev container to the .ssh folder on container
  when: ssh_keys_exist.stat.exists
  copy:
    src: "/workspaces/{{repo_name}}/defaults/.generated_keys/id_rsa"
    dest: "/root/.ssh/id_rsa"

- name: "cat pub key and register value in VAR when it already exists"
  when: ssh_keys_exist.stat.exists
  shell: 'cat /root/.ssh/id_rsa.pub' 
  register: ssh_key_pub

- name: Change file ownership for root/.ssh
  when: ssh_keys_exist.stat.exists
  ansible.builtin.file:
    path: /root/.ssh/id_rsa
    mode: '400'

- meta: end_play
  when: ssh_keys_exist.stat.exists

# IF No ssh key is present new one will generate

- name: "Generate New Key"
  shell: 'ssh-keygen -b 2048 -t rsa -f /root/.ssh/id_rsa -q -N ""'  

- name: "cat pub key and register value in VAR"
  shell: 'cat /root/.ssh/id_rsa.pub' 
  register: ssh_key_pub

- name: Creates .generated_keys hidden folder in defaults
  file:
      path: "/workspaces/{{repo_name}}/defaults/.generated_keys"
      state: directory

- name: "Save PUB SSH key to local workspace"
  shell: "cp /root/.ssh/id_rsa.pub /workspaces/{{repo_name}}/defaults/.generated_keys/id_rsa.pub"

- name: "Save Private SSH key to local workspace"
  shell: "cp /root/.ssh/id_rsa /workspaces/{{repo_name}}/defaults/.generated_keys/id_rsa"
