#  localhost play
- name: Check if Keys are already present
  stat:
    path: /workspaces/{{repo_name}}/defaults/.generated_keys/id_rsa
  register: ssh_keys_exist

- name: "cat pub key and register value in VAR when it already exists"
  when: ssh_keys_exist.stat.exists
  shell: 'cat /root/.ssh/id_rsa.pub' 
  register: ssh_key_pub

- meta: end_play
  when: ssh_keys_exist.stat.exists

# - name: Remove pub key (delete file)
#   ansible.builtin.file:
#     path: /root/.ssh/id_rsa.pub
#     state: absent
# - name: Remove private key (delete file)
#   ansible.builtin.file:
#     path: /root/.ssh/id_rsa
#     state: absent

- name: "Generate New Key"
  shell: 'ssh-keygen -b 2048 -t rsa -f /root/.ssh/id_rsa -q -N ""'  

- name: "cat pub key and register value in VAR"
  shell: 'cat /root/.ssh/id_rsa.pub' 
  register: ssh_key_pub

- name: Creates .generated_keys hidden folder in defaults
  file:
      path: "/workspaces/{{repo_name}}/defaults/.generated_keys"
      state: directory

- name: "Save PUB SSH key to local workspace"
  shell: "cp /root/.ssh/id_rsa.pub /workspaces/{{repo_name}}/defaults/.generated_keys/id_rsa.pub"

- name: "Save Private SSH key to local workspace"
  shell: "cp /root/.ssh/id_rsa /workspaces/{{repo_name}}/defaults/.generated_keys/id_rsa"
