#  localhost play

- name: Remove pub key (delete file)
  ansible.builtin.file:
    path: /root/.ssh/id_rsa.pub
    state: absent
- name: Remove private key (delete file)
  ansible.builtin.file:
    path: /root/.ssh/id_rsa
    state: absent

- name: "Generate New Key"
  shell: 'ssh-keygen -b 2048 -t rsa -f /root/.ssh/id_rsa -q -N ""' 

- name: "cat pub key and register value in VAR"
  shell: 'cat /root/.ssh/id_rsa.pub' 
  register: ssh_key_pub

- name: "cat private key and register value in VAR"
  shell: 'cat /root/.ssh/id_rsa' 
  register: ssh_key_private

- name: Creates generated_keys
  file:
      path: "/workspaces/JBE-Ansible/.generated_keys"
      state: directory

- name: "Save PUB SSH keys to local workspace"
  shell: "cp /root/.ssh/id_rsa.pub /workspaces/JBE-Ansible/.generated_keys/id_rsa.pub"

- name: "Save Private SSH keys to local workspace"
  shell: "cp /root/.ssh/id_rsa /workspaces/JBE-Ansible/.generated_keys/id_rsa"