# Network And Security
- name: "Set SSH Enviorment to alternate port"
  shell: "ufw allow ssh && \
            ufw allow {{ssh_port}}"

- name: "Download SSH Config"
  shell: "cd {{homedir}} && rm -rfv {{homedir}}/provision-new-env && git clone https://github.com/jtmb/provision-new-env.git"

- name: "Move SSH Config"
  shell: "cp {{homedir}}/provision-new-env/sshd_config /etc/ssh/sshd_config"

- name: Creates SSH hidden directory
  file:
      path: "{{homedir}}/.ssh"
      state: directory

- name: "Create SSH config from ssh_key_pub variable"
  shell: "echo {{ hostvars['localhost']['ssh_key_pub'] }} >> {{homedir}}/.ssh/id_rsa.pub"

- name: "Restart SSH Service"
  shell: "systemctl restart sshd"
