#  localhost play

- name: Remove pub key (delete file)
  ansible.builtin.file:
    path: /root/.ssh/id_rsa.pub
    state: absent
- name: Remove private key (delete file)
  ansible.builtin.file:
    path: /root/.ssh/id_rsa
    state: absent

- name: "Generate New Key"
  shell: 'ssh-keygen -b 2048 -t rsa -f /root/.ssh/id_rsa -q -N ""' 

- name: "cat key and register value in VAR"
  shell: 'cat /root/.ssh/id_rsa.pub' 
  register: ssh_key_pub