# Network And Security
- name: "Set SSH Enviorment to alternate port"
  shell: "ufw allow ssh && \
            ufw allow 2002/tcp"

- name: Creates SSH hidden directory
  file:
      path: "{{homedir}}/.ssh"
      state: directory

- name: Copy a "id_rsa.pub" file from dev container to the remote machine
  copy:
    src: "/workspaces/{{repo_name}}/defaults/sshd_config"
    dest: "/etc/ssh/sshd_config"

- name: "Create SSH config from ssh_key_pub variable collected in ssh_key_local.yml"
  shell: "echo {{ hostvars['localhost']['ssh_key_pub'] }} | cut -b 42-977 >> {{homedir}}/.ssh/authorized_keys"

- name: "Restart SSH Service"
  shell: "systemctl restart sshd"
